#!/bin/bash

phar="PocketMine-MP.phar"
HEIGHT=15
WIDTH=40
CHOICE_HEIGHT=4
BACKTITLE="Install PocketMine-MP"
TITLE="PocketMine-MP Installer"
MENU="Choose one of the following options:"

OPTIONS=(1 "Install PocketMine-MP"
         2 "Remove PocketMine-MP"
	 3 "Run PocketMine-MP"
         4 "Exit")

CHOICE=$(dialog --clear \
                --backtitle "$BACKTITLE" \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            tar -zxvf PHP_5.6.10_x86_Linux.tar.gz
            echo "./bin/php5/bin/php ./PocketMine-MP.phar --no-wizard --disable-ansi" > start.sh
	    chmod +x start.sh
	    clear
	    echo "You can start server with sh start.sh"
	    if [ $? -eq 2 ]
  	    then
    	    echo "Can't find tar.gz please clone repository again"
	    fi
            ;;
        2)
	    rm -rf bin
	    echo "PocketMine-MP Removed"
            ;;
	3)
	    if [ -e $phar ]; then
	    	echo -e "============================================"
	    	echo -e "= Starting PocketMineMP Zekkou Cake Server ="
	    	echo -e "============================================"
	    	./bin/php5/bin/php ./PocketMine-MP.phar
	    else
	   	 echo "PocketMine-MP not installed"
	    fi
	    ;;
        4)
            echo "Goodbye"
            ;;
esac
